server:
  servlet:
    context-path: /oa
  port: 8081


logging:
  level:
    root: info
    com.gcc.springBoot.controller: trace


spring:
  # 可以换行,但是第二行要向后缩进一下
  datasource:
    url: jdbc:mysql://localhost:3306/my_db_oa_sys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # 虽然只要引入了阿里巴巴的druid的starter,就会将默认的HikariCP替换掉,但是还是建议显示的写出来
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #指定Mybatis映射文件的位置
  mapper-locations: classpath:/mapper/*.xml
  # 指定配置类中下划线转驼峰的开启
  configuration:
    map-underscore-to-camel-case: true

redis:
  host: 192.168.88.100
  port: 6379
  password: null
  timeout: 30000
  # 连接池最大连接数（使用负值表示没有限制）
  maxTotal: 30
  # 最大空闲数
  maxIdle: 10
  # 连接池最大阻塞等待时间（使用负值表示没有限制）/ 获取连接时的最大等待毫秒数,小于零:阻塞不确定的时间,默认-1
  maxWaitMillis: 1500
  # 做空闲连接检测时，每次的采样数 / 每次释放连接的最大数目
  numTestsPerEvictionRun: 1024
  # 空闲连接的检测周期，单位为毫秒 / 释放连接的扫描间隔（毫秒）
  timeBetweenEvictionRunsMillis: 30000
  # 连接的最小空闲时间，达到此值后空闲连接将被移除
  minEvictableIdleTimeMillis: 1800000
  # 连接空闲多久后释放, 当空闲时间>该值&&空闲连接>最大空闲连接数=>直接释放
  softMinEvictableIdleTimeMillis: 10000
  # 向连接池借用连接时是否做连接有效性检测(Ping)无效连接将会被删除 / 在获取连接的时候检查有效性, 默认false
  testOnBorrow: true
  # 向连接池借用连接时是否做空闲检测，空闲超时的将会被移除 / 在空闲时检查有效性, 默认false
  testWhileIdle: true
  # 当连接池资源耗尽时，调用者是否需要等待。和maxWaitMillis对应，当它为true时，maxWaitMillis生效 / 连接耗尽时是否阻塞, false报异常,true阻塞直到超时, 默认true
  blockWhenExhausted: false

